Modified already uploaded notes, added new course notes (DIDC, PE, Si…
valerionew/triennale-elettronica-polimi pull request #30
Opened 2023-07-24 07:33 UTC by Lucaxc

…gnal Recovery)

Ho sistemato alcune cose dei vecchi appunti caricati precedentemente e aggiunto quelli di Digital (Bonfanti), Signal recovery e power electronics

- [x] Sto inviando nuovo materiale di cui detengo i diritti e accetto di rilasciarlo sotto la licenza [Creative Commons BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

2023-08-19 07:20 UTC, TIT8 requested changes

2023-08-19 07:20 UTC, TIT8 commented on index.html
> +  <li>Course Notes by <i>Luca Colombo</i> - <a href="4/ElectronicSystems/Electronic Systems.pdf" download>download</a> </li>
Dai pdf che hai caricato, il file ha ancora il nome tutto maiuscolo

2023-08-19 07:20 UTC, TIT8 commented on index.html
> +</ul>
Dovresti aggiungere DICD anche nella parte di html in alto dove vengono elencate le materie.

Così tipo:

![Screenshot (128)](https://github.com/valerionew/triennale-elettronica-polimi/assets/68781644/66c8e4e1-df35-42fa-b198-211a46b26a11)

Occhio solo all'id, nel tuo caso sarebbe **id=#DICD**

2023-08-19 07:20 UTC, TIT8 commented on index.html
> +
Ripeto quanto detto per DICD

2023-09-02 10:27 UTC, Lucaxc commented
Ciao, scusa il ritardo. Il file era già col nome corretto nella mia repo di git locale, probabilmente era un bug che ho fixato con dei commit poco eleganti. I nomi dovrebbero anche quelli essere stati sistemati :)

2023-09-15 09:56 UTC, closed without merging